### ISSUE TITLE
AWS EBS : ProcessFailedException

### ISSUE THREAD

**Issue by dhwlm** [verumconsilium/laravel-browsershot#14]
I'm getting this error

"""
The command "PATH=$PATH:/usr/local/bin NODE_PATH=/usr/local/bin/node /usr/local/bin/npm root -g /usr/local/bin/node '/var/app/current/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:///tmp/1163077786-0396427001571837477/index.html","action":"pdf","options":{"path":"/tmp/BrowsershotOutputgbSCqT.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"margin":{"top":"0mm","right":"0mm","bottom":"0mm","left":"0mm"}}}'" failed. ◀

Exit Code: 1(General error)

Working directory: /var/app/current/public

Output:
Error Output:
/var/app/current/vendor/spatie/browsershot/bin/browser.js:5
const [, , ...args] = process.argv;
^
SyntaxError: Unexpected token [
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3
"""

any help would be appreciated.

node -v = v0.12.2
npm -v = 2.7.4

**Comment by bsteps** [comment]
I used to get this error but i solved it by following the steps in https://github.com/spatie/browsershot

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

sudo apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

sudo npm install --global --unsafe-perm puppeteer

sudo chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium

the difference is it added this extra library "libgbm1" and node 12
