### ISSUE TITLE
Does it support laravel 6* ? 

### ISSUE THREAD

**Issue by sakjain02** [verumconsilium/laravel-browsershot#17]

**Comment by sgtpepper9907** [comment]
It hasn’t been tested on Laravel 6, but it should work fine. If you encounter any problems reopen this issue.

**Comment by sakjain02** [comment]
It says Argument 1 passed to Spatie\Browsershot\Browsershot::setNodeBinary() must be of the type string, null given

**Comment by damonbakker** [comment]
Same
`Argument 1 passed to Spatie\Browsershot\Browsershot::setNodeBinary() must be of the type string, null given`
