### ISSUE TITLE
waitForFunction chain throws an error

### ISSUE THREAD

**Issue by tfolio-vimal** [verumconsilium/laravel-browsershot#2]
I get this error : "Method VerumConsilium\\Browsershot\\PDF::waitForFunction() does not exists", when I ca;; waitForFunction along with other functions.

You have written that all of the chains of Browsershot would work fine, but this one doesn't

**Comment by sgtpepper9907** [comment]
The package was using an outdated version of Browsershot

**Comment by tfolio-vimal** [comment]
I got it.! thank you so much for your reply.!
