### ISSUE TITLE
using storeAs throwing  error after recent update

### ISSUE THREAD

**Issue by artin** [verumconsilium/laravel-browsershot#4]
We updated packages using <composer update) and browsershot showing error if we use storeAs option ....

**Undefined index: screenshot-filename.jpg**

from this file and  section :
/vendor/league/flysystem/src/Adapter/Local.php  line 350:
`        $success = chmod($location, $this->permissionMap[$type][$visibility]);`

this is our test code which was working before this update:
```
Screenshot::loadUrl($url)
	->windowSize(1024, 850)
         ->useJPG()
	->storeAs('public/',"screenshot-filename.jpg");
```

it actually taking screen shot but saving in another name and as png !

this is the ourput file:
ROCZJfQGkiXoeNrp7iA9W9xg7mSGRzDqs70NITJW.png

**Comment by artin** [comment]
Update:
I tried this on a clean Laravel 5.7 install and got the same result ... it seems there are issue with some recent laravel packages ...

**Comment by nickels** [comment]
Great package, unfortunately same issue here!

            "name": "laravel/framework",
            "version": "v5.7.8",

            "name": "verumconsilium/laravel-browsershot",
            "version": "v1.0.2",

**Comment by nickels** [comment]
https://github.com/verumconsilium/laravel-browsershot/pull/5

Should address the issue, not sure however if the putFileAs method works when the $filename is null.

**Comment by verumconsilium** [comment]
#5 fixed the issue. Added tests and some changes to @nickels contribution
Thanks for the support
