### ISSUE TITLE
Chained methods being ignored

### ISSUE THREAD

**Issue by jrmypttrsn** [verumconsilium/laravel-browsershot#8]
My current return statement:
```php
return PDF::loadView('pdfs.cert2', array('certificate' => $certificate))->inline($file_name);
```
works just fine. But chaining any methods from spatie's library before ``` ->inline()``` seem to be ignored. Chaining them after results in method does not exist errors.

Any idea what I may be doing wrong?

**Comment by verumconsilium** [comment]
`inline()`, `download()`, `save()` and `saveAs()` all return a value so it is impossible to keep chaining methods after that, you should call all chained methods before calling any of the previous ones

**Comment by verumconsilium** [comment]
I'm closing the issue since it is not really a problem with the package but feel free to comment of you have more questions

**Comment by sgtpepper9907** [comment]
What method are you trying to chain? And what error is it throwing ?

**Comment by jrmypttrsn** [comment]
At the moment, `->landscape()` is ignored (the pdf remains portrait) and if I put it after `->inline()` then I get **Method Illuminate\Http\Response::landscape does not exist**, which I would expect to happen.

**Comment by sgtpepper9907** [comment]
I just tested it on a Laravel 5.7 fresh installation and `landscape()` is working as expected. Is there any way I can replicate this issue?

**Comment by sgtpepper9907** [comment]
I will close this issue since there was no reply and the method seems to be working fine. Feel free to reopen it if you have more info on how to replicate the issue

**Comment by bencarrr** [comment]
I'm getting the same thing with both download and landscape

```
 PDF::loadView($view)->landscape()->download()
```

**Comment by PaulRotter** [comment]
The landscape() seemingly being ignored may be due to included bootstrap css. This may force page size to portrait. Set $enable-print-styles scss variable to false or specify page size: a4 landscape.
